sections:
  - name: "Scoreboare"
    link: "Scoreboard.html"
    image: "https://i.imgur.com/yUnE1J4.jpeg"
  - name: "Piloting"
    link: "Piloting.html"
    image: "https://i.imgur.com/8wVb3qV.jpeg"
  - name: "Autonomous"
    link: "Autonomous.html"
    image: "https://i.imgur.com/GvMfykV.jpeg"
  - name: "Teamwork"
    link: "Teamwork.html"
    image: "https://i.imgur.com/byMVuLJ.jpeg"
